In [252]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

In [253]:
PATH = "asteroid.csv"

In [254]:
df = pd.read_csv(PATH)

C:\Users\ponts\AppData\Local\Temp\ipykernel_20024\3476328945.py:1: DtypeWarning: Columns (0: pdes, 1: name, 2: prefix) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(PATH)

In [255]:
df.head()

         id    spkid       full_name  ...     sigma_per class      rms
0  a0000001  2000001         1 Ceres  ...  9.415900e-09   MBA  0.43301
1  a0000002  2000002        2 Pallas  ...  3.680700e-06   MBA  0.35936
2  a0000003  2000003          3 Juno  ...  3.107200e-06   MBA  0.33848
3  a0000004  2000004         4 Vesta  ...  1.274900e-06   MBA  0.39980
4  a0000005  2000005       5 Astraea  ...  3.490500e-06   MBA  0.52191

[5 rows x 45 columns]

In [256]:
print(df.shape)

(958524, 45)

In [257]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
id                     0
spkid                  0
full_name              0
pdes                   0
name              936460
prefix            958506
neo                    4
pha                19921
H                   6263
diameter          822315
albedo            823421
diameter_sigma    822443
orbit_id               0
epoch                  0
epoch_mjd              0
epoch_cal              0
equinox                0
e                      0
a                      0
q                      0
i                      0
om                     0
w                      0
ma                     1
ad                     4
n                      0
tp                     0
tp_cal                 0
per                    4
per_y                  1
moid               19921
moid_ld              127
sigma_e            19922
sigma_a            19922
sigma_q            19922
sigma_i            19922
sigma_om           19922
sigma_w            19922
sigma_ma           19922
sigma_ad           19926
sigma_n            19922
sigma_tp           19922
sigma_per          19926
class                  0
rms                    2
dtype: int64

In [258]:
print("Duplicate rows in the dataset:", df.duplicated().sum())

Duplicate rows in the dataset: 0

In [259]:
# Remove rows with ANY NaN values
df_no_nulls = df.dropna()

In [260]:
print("Dataset shape after removing rows with NaN values:", df_no_nulls.isnull().sum())
print("Dataset shape after removing rows with NaN values:", df_no_nulls.shape)

Dataset shape after removing rows with NaN values: id                0
spkid             0
full_name         0
pdes              0
name              0
prefix            0
neo               0
pha               0
H                 0
diameter          0
albedo            0
diameter_sigma    0
orbit_id          0
epoch             0
epoch_mjd         0
epoch_cal         0
equinox           0
e                 0
a                 0
q                 0
i                 0
om                0
w                 0
ma                0
ad                0
n                 0
tp                0
tp_cal            0
per               0
per_y             0
moid              0
moid_ld           0
sigma_e           0
sigma_a           0
sigma_q           0
sigma_i           0
sigma_om          0
sigma_w           0
sigma_ma          0
sigma_ad          0
sigma_n           0
sigma_tp          0
sigma_per         0
class             0
rms               0
dtype: int64
Dataset shape after removing rows with NaN values: (0, 45)

In [261]:
df_no_nulls.head()

Empty DataFrame
Columns: [id, spkid, full_name, pdes, name, prefix, neo, pha, H, diameter, albedo, diameter_sigma, orbit_id, epoch, epoch_mjd, epoch_cal, equinox, e, a, q, i, om, w, ma, ad, n, tp, tp_cal, per, per_y, moid, moid_ld, sigma_e, sigma_a, sigma_q, sigma_i, sigma_om, sigma_w, sigma_ma, sigma_ad, sigma_n, sigma_tp, sigma_per, class, rms]
Index: []

- Dropping rows by searching for null rows removes every entry

- Since my main focus on the diameter of Asteroids, missing asteroid data will only hinder my research
    - So i will remove rows with missing diameters

In [262]:
df_no_diameter_nulls = df.dropna(subset=['diameter'])

In [263]:
df_no_diameter_nulls.head()

         id    spkid       full_name  ...     sigma_per class      rms
0  a0000001  2000001         1 Ceres  ...  9.415900e-09   MBA  0.43301
1  a0000002  2000002        2 Pallas  ...  3.680700e-06   MBA  0.35936
2  a0000003  2000003          3 Juno  ...  3.107200e-06   MBA  0.33848
3  a0000004  2000004         4 Vesta  ...  1.274900e-06   MBA  0.39980
4  a0000005  2000005       5 Astraea  ...  3.490500e-06   MBA  0.52191

[5 rows x 45 columns]

In [264]:
print("Dataset shape after removing rows with NaN values:", df_no_diameter_nulls.isnull().sum())

Dataset shape after removing rows with NaN values: id                     0
spkid                  0
full_name              0
pdes                   0
name              121047
prefix            136209
neo                    0
pha                    0
H                   4164
diameter               0
albedo              1109
diameter_sigma       128
orbit_id               0
epoch                  0
epoch_mjd              0
epoch_cal              0
equinox                0
e                      0
a                      0
q                      0
i                      0
om                     0
w                      0
ma                     0
ad                     0
n                      0
tp                     0
tp_cal                 0
per                    0
per_y                  0
moid                   0
moid_ld                0
sigma_e                0
sigma_a                0
sigma_q                0
sigma_i                0
sigma_om               0
sigma_w                0
sigma_ma               0
sigma_ad               0
sigma_n                0
sigma_tp               0
sigma_per              0
class                  0
rms                    0
dtype: int64

In [265]:
### Drop unnecessary columns

columns_to_drop = [
    "spkid", "fullname", "pdes", "name", "prefix",
    "diameter_sigma",
    "epoch_mjd", "epoch_cal",
    "orbit_id"
    "tp_cal",
    "per_y",
    "moid_ld"
]

cols_to_drop = [c for c in columns_to_drop if c in df_no_diameter_nulls.columns]
df_no_diameter_nulls = df_no_diameter_nulls.drop(columns=cols_to_drop)

In [266]:
df_no_diameter_nulls.head()

         id       full_name neo pha  ...      sigma_tp     sigma_per  class      rms
0  a0000001         1 Ceres   N   N  ...  3.782900e-08  9.415900e-09    MBA  0.43301
1  a0000002        2 Pallas   N   N  ...  4.078700e-05  3.680700e-06    MBA  0.35936
2  a0000003          3 Juno   N   N  ...  3.528800e-05  3.107200e-06    MBA  0.33848
3  a0000004         4 Vesta   N   N  ...  4.103700e-06  1.274900e-06    MBA  0.39980
4  a0000005       5 Astraea   N   N  ...  3.474300e-05  3.490500e-06    MBA  0.52191

[5 rows x 36 columns]

- Dataframe is now free of Null diameters.

### 2. Categorical Encoding

In [267]:
### Set ID as index
df = df_no_diameter_nulls.set_index('id')

y_diameter = df['diameter']

In [268]:
y_diameter.head()

id
a0000001    939.400
a0000002    545.000
a0000003    246.596
a0000004    525.400
a0000005    106.699
Name: diameter, dtype: float64

### Label encoding vs One-Hot Encoding

1. Label encoding creates an order to the categories

2. One-Hot Encoder simply categorises the data with no ranking/order

In [269]:
### Testing which columns to encode

# Check which columns are categorical and need encoding
columns = ['neo', 'pha', 'class']

for col in columns:
    print("=" * 40)
    print("Column: ", col)
    print(df_no_diameter_nulls[col].value_counts())

========================================
Column:  neo
neo
N    135360
Y       849
Name: count, dtype: int64
========================================
Column:  pha
pha
N    135988
Y       221
Name: count, dtype: int64
========================================
Column:  class
class
MBA    124971
OMB      7521
TJN      1873
IMB       566
APO       486
MCA       358
AMO       268
ATE        95
CEN        51
TNO        12
AST         8
Name: count, dtype: int64

In [270]:
def get_unique_values(df, column):
    unique_values = df[column].unique()
    #print(f"Unique values in column '{column}': {unique_values}")
    return unique_values

for col in columns:
    print(get_unique_values(df_no_diameter_nulls, col))

<StringArray>
['N', 'Y']
Length: 2, dtype: str
<StringArray>
['N', 'Y']
Length: 2, dtype: str
<StringArray>
['MBA', 'OMB', 'MCA', 'AMO', 'IMB', 'TJN', 'CEN', 'APO', 'ATE', 'AST', 'TNO']
Length: 11, dtype: str

In [271]:
def encode_categorical_columns(df, columns):
    encoded_df = df.copy()
    binary_cols = []
    one_hot_cols = []

    for col in columns:
        if col not in encoded_df.columns:
            continue

        n_unique = encoded_df[col].nunique(dropna=True)

        if n_unique == 2:
            le = LabelEncoder()
            encoded_df[col] = le.fit_transform(encoded_df[col])
            binary_cols.append(col)
        elif n_unique > 2:
            one_hot_cols.append(col)

    if one_hot_cols:
        encoded_df = pd.get_dummies(encoded_df, columns=one_hot_cols, drop_first=True)

    return encoded_df, binary_cols, one_hot_cols

encoded_df, binary_cols, one_hot_cols = encode_categorical_columns(df_no_diameter_nulls, columns)
print("Label-encoded columns:", binary_cols)
print("One-hot encoded columns:", one_hot_cols)
encoded_df.head()

Label-encoded columns: ['neo', 'pha']
One-hot encoded columns: ['class']

         id       full_name  neo  ...  class_OMB  class_TJN  class_TNO
0  a0000001         1 Ceres    0  ...      False      False      False
1  a0000002        2 Pallas    0  ...      False      False      False
2  a0000003          3 Juno    0  ...      False      False      False
3  a0000004         4 Vesta    0  ...      False      False      False
4  a0000005       5 Astraea    0  ...      False      False      False

[5 rows x 45 columns]